Repository 809bakery/SCON-Frontend, pull requests merged in 2024-07, with the labels that each got.

#10 Feat/#9 a2hs
  public/manifest.json
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-f1770938.js
  src/app/(auth)/login/page.tsx
  src/app/layout.tsx
  src/components/.gitkeep
  src/components/a2hs/index.tsx
  src/static/svg/a2hs-icon.svg
  src/types/.gitkeep
  src/types/pwa.d.ts
Labels: feat

#13 Design/#2 회원가입 페이지 UI 디자인
  .eslintrc.json
  src/app/(auth)/signup/[step]/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/steps/BasicInfoStep.tsx
  src/app/(auth)/signup/steps/JoinStep.tsx
  src/app/(auth)/signup/steps/MoreInfoStep.tsx
  src/app/(auth)/signup/steps/ProfileStep.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/Step.tsx
  src/components/timer.tsx
  src/static/svg/checked-icon.svg
  src/static/svg/default-profile.svg
  src/static/svg/hide-icon.svg
  src/static/svg/progress/step1.svg
  src/static/svg/progress/step2.svg
  src/static/svg/progress/step3.svg
  src/static/svg/progress/step4.svg
  src/static/svg/required-star.svg
  src/static/svg/show-icon.svg
  src/static/svg/unchecked-icon.svg
  src/static/svg/upload-icon.svg
  tailwind.config.ts
  yarn.lock
Labels: design

#18 Feat/#8 소셜 로그인 redirect page
  .gitignore
  public/sw.js
  public/sw.js.map
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  src/app/(auth)/login/page.tsx
  src/app/(auth)/login/social/[service]/page.tsx
  src/app/layout.tsx
  yarn.lock
Labels: feat

#20 Design/#19 sidebar
  src/app/page.tsx
  src/components/sidebar/index.tsx
  src/components/sidebar/item/index.tsx
  src/components/sidebar/profile/index.tsx
  src/static/svg/chevron-right.svg
  src/static/svg/ovner-mark.svg
  src/static/svg/sidebar-close.svg
  src/static/svg/sidebar-profile.svg
Labels: design

#22 Design/#21_login svg 수정
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/page.tsx
  src/components/sidebar/index.tsx
  src/static/svg/main-icon.svg
Labels: design

#24 Design/#14 메인페이지 UI 작업
  public/images/carouselSlideImage1.jpg
  public/images/carouselSlideImage2.jpg
  public/images/carouselSlideImage3.jpg
  public/images/carouselSlideImage4.jpg
  public/images/carouselSlideImage5.jpg
  src/app/(auth)/signup/steps/ProfileStep.tsx
  src/app/(home)/main/page.tsx
  src/app/(home)/menu/page.tsx
  src/app/(home)/search/page.tsx
  src/app/layout.tsx
  src/components/Carousel.tsx
  src/components/Navbar/index.tsx
  src/features/.gitkeep
  src/features/event/components/stage/AllStage.tsx
  src/features/event/components/stage/MyStage.tsx
  src/features/event/components/stage/RecommendStage.tsx
  src/features/event/components/stage/index.tsx
  src/features/event/types/StageCategory.ts
  src/static/svg/dummy-contents.svg
  src/static/svg/indicator-icon.svg
  src/static/svg/navbar/alarm-icon.svg
  src/static/svg/navbar/menu-icon.svg
  src/static/svg/navbar/search-icon.svg
  tsconfig.json
  yarn.lock
Labels: design

#32 Design/#15 회원가입 34단계 UI 작업
  .eslintrc.json
  src/app/(auth)/signup/[step]/page.tsx
  src/app/(auth)/signup/steps/JoinStep.tsx
  src/app/(auth)/signup/steps/MoreInfoStep.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/static/gif/checked.gif
Labels: design

#35 Design/#33 card and footer
  public/dummy/dummy-poster-behemoth.svg
  public/dummy/dummy-poster-bigbang.jpg
  public/dummy/dummy-poster-echidna1.svg
  public/dummy/dummy-poster-echidna2.svg
  public/dummy/dummy-poster-kamen.svg
  public/dummy/dummy-poster-newjeans.jpg
  public/dummy/dummy-poster-raid.svg
  public/dummy/dummy-poster-skirt.jpg
  public/dummy/dummy-poster-yerin.jpg
  public/images/carouselImage.jpg
  src/app/(auth)/login/page.tsx
  src/app/(home)/main/page.tsx
  src/components/Carousel.tsx
  src/components/footer/index.tsx
  src/constants/.gitkeep
  src/constants/dummy.ts
  src/features/event/components/stage/AllStage.tsx
  src/features/event/components/stage/Card/index.tsx
  src/features/event/components/stage/MyStage.tsx
  src/features/event/components/stage/RecommendStage.tsx
  tailwind.config.ts
Labels: design

#36 Design/#34 검색 페이지 UI 구현 및 기능 구현
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/signup/[step]/page.tsx
  src/app/(home)/search/_components/Filter.tsx
  src/app/(home)/search/_components/OvenCard.tsx
  src/app/(home)/search/_components/SearchBar.tsx
  src/app/(home)/search/_components/StageCard.tsx
  src/app/(home)/search/_components/Tab.tsx
  src/app/(home)/search/page.tsx
  src/constants/search/index.ts
  src/static/img/dummy/search/dummy-oven-profile1.jpg
  src/static/img/dummy/search/dummy-oven-profile2.jpg
  src/static/img/dummy/search/dummy-oven-profile3.jpg
  src/static/img/dummy/search/dummy-oven-profile4.jpg
  src/static/img/dummy/search/dummy-oven-profile5.jpg
  src/static/img/dummy/search/dummy-stage-profile1.jpg
  src/static/img/dummy/search/dummy-stage-profile2.jpg
  src/static/img/dummy/search/dummy-stage-profile3.jpg
  src/static/img/dummy/search/dummy-stage-profile4.jpg
  src/static/svg/arrow-left-icon.svg
  src/static/svg/dummy/search/dummy-search-oven1.svg
  src/static/svg/dummy/search/dummy-search-oven2.svg
  src/static/svg/dummy/search/dummy-search-oven3.svg
  src/static/svg/dummy/search/dummy-search-oven4.svg
  src/static/svg/dummy/search/dummy-search-oven5.svg
  src/static/svg/search-icon.svg
  tailwind.config.ts
Labels: design, feat

#38 FEAT/#37 Navbar 기능을 컴포넌트화하여 layout level에서 사용
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/signup/[step]/page.tsx
  src/app/(home)/main/page.tsx
  src/app/(home)/search/page.tsx
  src/app/layout.tsx
  src/components/Navbar/NavbarWithGoback.tsx
  src/components/Navbar/NavbarWithoutGoback.tsx
  src/components/Navbar/index.tsx
Labels: chore, feat

#41 Bug/#26 pwa view
  src/app/(auth)/login/page.tsx
  src/app/(home)/main/page.tsx
  src/app/layout.tsx
  src/components/a2hs/index.tsx
  src/features/event/components/stage/Card/index.tsx
  src/static/svg/social/google-login.svg
Labels: design, fix

#42 Design/#39 오븐 둘러보기 및 오븐 상세보기 페이지 UI 작업
  .eslintrc.json
  next.config.mjs
  src/app/(home)/search/_components/Filter.tsx
  src/app/(home)/search/_components/Tab.tsx
  src/app/(home)/search/page.tsx
  src/app/oven/detail/OvenDetailCard.tsx
  src/app/oven/detail/[name]/_components/FollowButton.tsx
  src/app/oven/detail/[name]/_components/InfoField.tsx
  src/app/oven/detail/[name]/page.tsx
  src/app/oven/detail/page.tsx
  src/components/Navbar/NavbarWithGoback.tsx
  src/components/Navbar/index.tsx
  src/components/Searchbar/index.tsx
  src/components/sidebar/index.tsx
  src/constants/dummy.ts
  src/constants/search/index.ts
  src/static/img/dummy/search/dummy-jururu-stage1.jpg
  src/static/img/dummy/search/dummy-jururu-stage2.jpg
  src/static/img/dummy/search/dummy-oven-profile10.jpg
  src/static/img/dummy/search/dummy-oven-profile6.jpg
  src/static/img/dummy/search/dummy-oven-profile7.jpg
  src/static/img/dummy/search/dummy-oven-profile8.jpg
  src/static/img/dummy/search/dummy-oven-profile9.jpg
  src/static/svg/heart-fill-icon.svg
  src/static/svg/heart-unfill-icon.svg
  tailwind.config.ts
Labels: design

#46 Refactor/#43 1차 정기 리팩토링
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/steps/BasicInfoStep.tsx
  src/app/(auth)/signup/steps/JoinStep.tsx
  src/app/(auth)/signup/steps/MoreInfoStep.tsx
  src/app/(auth)/signup/steps/ProfileStep.tsx
  src/components/AlertButton.tsx/index.tsx
  src/components/Carousel.tsx
  src/components/Navbar/NavbarWithGoback.tsx
  src/components/a2hs/index.tsx
  src/components/sidebar/index.tsx
  src/components/sidebar/item/index.tsx
  src/constants/regex/index.ts
  src/features/event/components/stage/AllStage.tsx
  src/features/event/components/stage/MyStage.tsx
  src/features/event/components/stage/RecommendStage.tsx
  src/features/event/components/stage/StageList.tsx
  src/static/img/dummy/profile/default-profile.jpg
  src/static/svg/dummy/dummy-profile-image.svg
  src/static/svg/dummy/dummy-stage-contents.svg
  src/static/svg/dummy/search/dummy-search-oven1.svg
  src/static/svg/dummy/search/dummy-search-oven2.svg
  src/static/svg/dummy/search/dummy-search-oven3.svg
  src/static/svg/dummy/search/dummy-search-oven4.svg
  src/static/svg/dummy/search/dummy-search-oven5.svg
  src/static/svg/heart-fill-icon.svg
Labels: refactoring

#48 Design/#47 오븐 디테일 커뮤니티 탭 구현
  public/dummy/dummy-oven-detail-community1.jpg
  public/dummy/dummy-oven-detail-community2.png
  public/dummy/dummy-oven-profile.jpg
  src/app/oven/detail/[name]/_components/CommunityContentCard.tsx
  src/app/oven/detail/[name]/_components/CommunityTab.tsx
  src/app/oven/detail/[name]/_components/InfoTab.tsx
  src/app/oven/detail/[name]/page.tsx
Labels: design, feat

#51 Design/#49 오븐 스테이지 리스트의 타입별 페이지 UI
  public/dummy/dummy-stage-pick0.jpg
  public/dummy/dummy-stage-pick1.jpg
  public/dummy/dummy-stage-pick2.jpg
  public/dummy/dummy-stage-pick3.jpg
  public/dummy/dummy-stage-pick4.jpg
  src/app/(auth)/signup/steps/BasicInfoStep.tsx
  src/app/(home)/search/_components/Filter.tsx
  src/app/(home)/search/_components/StageCard.tsx
  src/app/(home)/search/_components/Tab.tsx
  src/app/(home)/search/page.tsx
  src/app/oven/detail/[name]/_components/InfoTab.tsx
  src/app/oven/detail/page.tsx
  src/app/stage/list/[type]/_components/AllStageList.tsx
  src/app/stage/list/[type]/_components/MyStageList.tsx
  src/app/stage/list/[type]/_components/PickStageList.tsx
  src/app/stage/list/[type]/page.tsx
  src/components/Navbar/index.tsx
  src/components/Searchbar/index.tsx
  src/components/loader/index.tsx
  src/constants/search/index.ts
  src/features/event/components/stage/AllStage.tsx
  src/features/event/components/stage/MyStage.tsx
  src/features/event/components/stage/RecommendStage.tsx
  src/static/img/dummy/stagelist/dummy-stage-pick-thumbnail.jpg
Labels: design, feat
